### ISSUE TITLE
[HELP] Support for react-rails

### ISSUE THREAD

**Issue by 3den** [Shopify/sprockets-commoner#23]
I am having a lot of trouble to get this gem to work with server side rendering on react-rails, also seems like first rendering after reload seems very slow. I there some way to get react rails to work with this?

**Comment by 3den** [comment]
@bouk where did the es2015 preset worked well in your project? The spread `...` operator did not work on my project, after adding `"plugins": ["transform-es2015-spread"]` assets:precompile works but on the front end i get an error...

**Comment by bouk** [comment]
This gem is pretty much incompatible with `react-rails`, as react-rails also does transpilation of JavaScript, which will probably mess with this gem. Server-side rendering is also not something that this gem supports

**Comment by bouk** [comment]
Going to close this as `react-rails` is fundamentally incompatible with this gem. Something akin to it could be build on top of this gem, however.

**Comment by 3den** [comment]
@bouk I was able to get react-rails to work fine, even the server side render, my only issue now is because i have to run assets:precompile and restart the server for every javascript change.
