### ISSUE TITLE
Schmooze throws `Cannot read property 'constant' of undefined` for dynamic requires

### ISSUE THREAD

**Issue by tessalt** [Shopify/sprockets-commoner#40]
Including a package that depended on https://github.com/component/closest/blob/master/index.js lead to this cryptic error when a require wrapped in a try/catch was encountered. 

If we're only supporting static requires a better error would be helpful. 

@bouk cc @tedtate @tanema

**Comment by bouk** [comment]
That module does some funky things with rewiring what is included, but I can see what I can do https://github.com/component/closest/blob/master/package.json
