### ISSUE TITLE
Adding `javascripts` directory to paths?

### ISSUE THREAD

**Issue by mockdeep** [Shopify/sprockets-commoner#45]
Is there a configuration to add the `javascripts` directory to our paths so that we can avoid having to relative `require '../../../helpers/stuff'`?

**Comment by bouk** [comment]
It should already work, `javascripts` is in the sprockets load path which is passed to resolve https://github.com/Shopify/sprockets-commoner/blob/7180a07f1c3ac0d7d9abf59bd3b270a87f535bf5/lib/sprockets/commoner/processor.rb#L205

**Comment by mockdeep** [comment]
Ah, okay. Turns out it was a `.jsx` file. When I renamed it to `.js` it moved on to another error, so I may be back with another issue soon.
